name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Скачать проект
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установить PyInstaller
        run: pip install pyinstaller

      - name: Собрать .exe
        run: pyinstaller --noconsole --onefile Игра.py

      - name: Загрузить exe
        uses: actions/upload-artifact@v4
        with:
          name: cyberhero-game
          path: dist/Игра.exe
